{{- if .Values.blockdiag.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kroki.fullname" . }}-bpmn
  namespace: {{ .Values.namespace.name }}
  labels:
    app: bpmn
    {{- include "kroki.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.bpmn.replicaCount }}
  selector:
    matchLabels:
      app: bpmn
      {{- include "kroki.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.bpmn.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: bpmn
        {{- include "kroki.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.bpmn.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kroki.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.bpmn.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-bpmn
          securityContext:
            {{- toYaml .Values.bpmn.securityContext | nindent 12 }}
          image: "{{ .Values.bpmn.image.repository }}:{{ .Values.bpmn.image.tag | default .Values.image.tag }}"
          imagePullPolicy: {{ .Values.bpmn.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8003
              protocol: TCP
          resources:
            {{- toYaml .Values.bpmn.resources | nindent 12 }}
      {{- with .Values.bpmn.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bpmn.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bpmn.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
