apiVersion: v1
kind: Service
metadata:
  name: {{ include "kroki.fullname" . }}-kroki
  namespace: {{ .Values.namespace.name }}
  labels:
    app: kroki
    {{- include "kroki.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: kroki
    {{- include "kroki.selectorLabels" . | nindent 4 }}
