apiVersion: v1
data:
  nginx.conf: |
    events {
      worker_connections  1024;
    }
    http {
      server {
        listen 80;
        location / {
          return 200 "===============================\n\nThis is your helm deploy! ${podname} ${myvar}\n\n===============================\n";
        }
      }
    }
kind: ConfigMap
metadata:
  name: {{ include "test-app.fullname" . }}
