name: kubeval Charts

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  kubeval-chart:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s:
          - v1.16.8
          - v1.17.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh
